here I will add all new lines from config.php(but I'll still update config)

rev 69
$config['site']['check_titles']= FALSE ; /// if true only titles from array belowwill be generated by headline script
$config['site']['allowed_titles'] = array();
?
